name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering
  schedule:
    - cron: "0 * * * *"  # Run feature extraction every hour
    - cron: "0 0 * * *"  # Run model training every day at midnight

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [ "feature_extraction.py", "train_model.py" ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyarrow  # Ensure pyarrow is installed
        pip install hopsworks[python]  # Install Hopsworks with Python dependencies, including Apache Arrow

    - name: Run the appropriate script
      run: |
        python ${{ matrix.script }}
