name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering
  schedule:
    - cron: "0 * * * *"  # Run feature extraction every hour
    - cron: "0 0 * * *"  # Run model training every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # or the Python version you're using
        
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run feature extraction script
      run: python feature_extraction.py


  model_training:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn hopsworks

      - name: Run training script
        run: |
          python train_model.py
